name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check encoded string length
        run: echo "${{ secrets.KEYSTORE_BASE_64 }}" | wc -c
      - name: Create keystore directory
        run: mkdir -p keystore

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/keystore.jks'
          encodedString: ${{ secrets.KEYSTORE_BASE_64 }}
      - name: List files
        run: ls -la keystore 
