name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Bundle 'release' with Gradle
        run: ./gradlew assembleRelease 
      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE_64 }}
          alias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}  
        env:
        # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Check path
        run: basename "$(pwd)"

      - name: Rename signed APK file
        id: rename_apk
        run: |
          cd app/build/outputs/apk/release
          for file in *unsigned-signed.apk; do
            echo "Processing file: $file"
            mv "${file}" "${file%-unsigned-signed.apk}.apk"
            echo "Renamed $file to ${file%-unsigned-signed.apk}.apk"
            echo "final_name=${file%-unsigned-signed.apk}.apk" >> $GITHUB_OUTPUT
          done
          echo "Files after renaming:"
          ls -la

        
        
      - name: Check path
        run: basename "$(pwd)"

      - run: echo "Build status report=${{ job.status }}."

      - run: echo "${{steps.rename_apk.outputs.final_name}}"
      
      - name: Upload App Bundle
        uses: actions/upload-artifact@v1
        with:
          name: aab
          path: "app/build/outputs/apk/release/${{steps.rename_apk.outputs.final_name}}"

      - run: echo "${SIGNED_RELEASE_FILE}"
