name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Bundle 'release' with Gradle
        run: ./gradlew assembleRelease 
      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE_64 }}
          alias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}  
        env:
        # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Check path
        run: basename "$(pwd)"

      - name: Rename signed APK file
        run: |
          cd app/build/outputs/apk/release
          for file in *-signed.apk; do
            echo "Processing file: $file"
            mv "${file}" "${file%-signed.apk}.apk"
            echo "Renamed $file to ${file%-signed.apk}.apk"
          done
          echo "Files after renaming:"
          ls -la

        id: rename_apk
        
      - name: Check path
        run: basename "$(pwd)"

      - run: echo "Build status report=${{ job.status }}."
      
      - name: Upload App Bundle
        uses: actions/upload-artifact@v1
        with:
          name: aab
          path: app/build/outputs/apk/release/ContentGenie-v1--release-unsigned.apk

      - run: echo "${SIGNED_RELEASE_FILE}"
