name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Bundle 'release' with Gradle
        run: ./gradlew assembleRelease 
      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE_64 }}
          alias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}  
        env:
        # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"


      - name: Rename AAB
        id: rename_aab
        run: |
          # Read the output file name
          SIGNED_FILE="${{steps.build.outputs.signedReleaseFile}}"
          RENAMED_FILE="${SIGNED_FILE%-signed.apk}.apk"
          mv "$SIGNED_FILE" "$RENAMED_FILE"
          echo "Renamed file: $RENAMED_FILE"
          echo "::set-output name=renamedReleaseFile::$RENAMED_FILE"

      - name: Upload Renamed AAB
        uses: actions/upload-artifact@v3
        with:
          name: renamed-release
          path: ${{steps.rename_aab.outputs.renamedReleaseFile}}
