
# APK Build workflow

name: Build APK

on:
  push:
    branches:
      - main
      - 'beta/*'
      - 'release/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Checkout code
        uses: actions/checkout@v4
      
      - run: echo "Setting up JDK" 
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_BASE_64 }}

        run: |
          mkdir -p secrets
          echo $ENCODED_KEYSTORE > secrets/keystore-b64.txt
          base64 -d secrets/keystore-b64.txt > secrets/keystore.jks

      - run: echo "Building Debug APK."  
      - name: Build with Gradle
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.SIGNING_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.SIGNING_ALIAS_PASSWORD }}
        run: chmod +x gradlew && ./gradlew assembleRelease
      - run: echo "Build status report=${{ job.status }}."

      - name: Get release file apk path
        id: releaseApk
        run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT
      
      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ steps.releaseApk.outputs.apkfile }}
          
      - name: Expose app version name
        run: echo "VERSION_NAME=$( ./gradlew -q app:printVersionName )" >> $GITHUB_ENV

      - name: Create app release
        uses: softprops/action-gh-release@v1
        with: 
          generate_release_notes: true
          files: app/build/outputs/apk/release/*.apk
          tag_name: ${{ env.VERSION_NAME }}
          name: ${{ env.VERSION_NAME }}
