name: Build Debug APK (Manual)

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Choose the build type"
        required: true
        default: "debug"
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Cache Gradle for faster builds
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Grant execute permission for Gradlew
      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      # 5. Build APK
      - name: Build ${{ github.event.inputs.buildType }} APK
        run: ./gradlew assemble${{ github.event.inputs.buildType == 'release' && 'Release' || 'Debug' }}

      # 6. Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.event.inputs.buildType }}-apk
          path: app/build/outputs/apk/${{ github.event.inputs.buildType }}/app-${{ github.event.inputs.buildType }}.apk
